#nodes-7000.conf
port 7010
bind 0.0.0.0
cluster-enabled yes
cluster-config-file nodes-7000.conf
cluster-node-timeout 3000
appendonly yes
requirepass xxxx
masterauth xxxx
protected-mode no
# cluster-announce-ip 127.0.0.1
# cluster-announce-port 7000
# cluster-announce-bus-port 17000

#nodes-7001.conf
port 7011
bind 0.0.0.0
cluster-enabled yes
cluster-config-file nodes-7001.conf
cluster-node-timeout 3000
appendonly yes
requirepass xxxx
masterauth xxxx
protected-mode no
# cluster-announce 옵션 주석 처리
# cluster-announce-ip 127.0.0.1
# cluster-announce-port 7001
# cluster-announce-bus-port 17001

#nodes-7002.conf
port 7012
bind 0.0.0.0
cluster-enabled yes
cluster-config-file nodes-7002.conf
cluster-node-timeout 3000
appendonly yes
requirepass xxxx
masterauth xxxx
protected-mode no
# cluster-announce 옵션 주석 처리
# cluster-announce-ip 127.0.0.1
# cluster-announce-port 7002
# cluster-announce-bus-port 17002
