jwt:
  secret:
    access: "w7uGmFxgOlFS9T+gFynHk7jB6mI/eA9WgjG5o9gB8uI="
    refresh: "w7uGmFxgOlFS9T+gFynHk7jB6mI/eA9WgjG5o9gB8uI="

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/mydatabase    # 테스트용 DB URL (실제 테스트 환경에 맞게 수정)
    username: dbuser                                 # 테스트용 DB 사용자
    password: dbpassword                             # 테스트용 DB 비밀번호

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
